---

- hosts: localhost

  pre_tasks:
    - name: Include configuration
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - config.yml
            - default.config.yml
          skip: true
      tags: ['always']

  roles:
    - role: mac
      tags: [homebrew, max, settings, shell]
    - role: linux
      tags: [ssh]
